### ISSUE TITLE
Option for borderless TOC?

### ISSUE THREAD

**Issue by eddelbuettel** [atusy/minidown#17]
Thanks for minidown, it is a really neat and useful self-contained setup.  I quite like the styles.  

I was wondering how you would feel about borderless floating TOCs?  For example the _water_ style is so light and clean and crisp that I would feel it could enhance it.

My CSS skills are pretty limited -- I tried to fried where the TOC may be defined but didn't find a spot for a quick-and-dirty change. What are your thoughts?

**Comment by atusy** [comment]
Thanks for the suggestion, and I agree with you.
Let me consider whether to remove the border for floating ToC or to provide option for that.

I remember that I added the border because I wanted to distinguish content and ToC when ToC is not floating.
Note that `toc_float: true` floats the ToC only if the viewport (window size) has width larger than 900px.


For now, you may include following chunk in your Rmd file to remove the border from ToC.
This will remove the border regardless of `toc_float`.

````
```{css, echo=FALSE}
nav > ul {border: none}
```
````

If you want to keep the border when toc is not floating, try

````
```{css, echo=FALSE}
@media screen and (min-width: 900px) {
  nav > ul {border: none}
}
```
````
