### ISSUE TITLE
Is this the expected function of `summary.results`?

### ISSUE THREAD

**Issue by Doubt-0KB** [atusy/minidown#86]
Hi, atusy.
First of all, thank you very much for your great package! It's very helpful for me to be able to create my reports without spending extra time for design.

Well, I have a question about an chunk option `summary.results`.
I read your introduction about 'minidown' (https://minidown.atusy.net/?framework=sakura&theme=default#change-summary-text) and tried to use the option to rewrite "Results" labels, but it didn't work. This is an example.

    ```{r, summary.results="Fig"}
    plot(iris[, 1:2])
    ```

So, I checked the file "hook-results-folding.R", and found the part that was probably wrong.

line 37-44

    opening <- c(
      show = " open", hide = ""
    )[match.arg(options$results.folding, c("show", "hide"))]
    summary <- if (is.null(options$summary.results)) {
      "Results"
    } else {
      no_linebreaks(options$results.summary)
    }

There are `summary.results` and `results.summary`.
Is this a wrong? Or is it the expected function?

(Supplement: This worked without problems.)

    ```{r, summary.results=T, results.summary="Fig"}
    plot(iris[, 1:2])
    ```

**Comment by atusy** [comment]
Thanks for using **minidown** and debugging!! I'm so glad!!
This is my mistake and will fix in #87.

I think I confused myself because `results.folding` and `summary.results` have opposite orders...
I remember `results.folding` comes from `result_folding` argument of `mini_document()`, and `summary.results` come from other chunk options...
I am not yet for the decision, but may update the names in the future...

Anyway, thanks again!

**Comment by Doubt-0KB** [comment]
Thanks for your quick response!
And I see... it certainly looks confusing. I hope you can solve it for the better.
